### ISSUE TITLE
When using peekInsets, the tracking area also gets smaller...

### ISSUE THREAD

**Issue by Janne-M** [cbpowell/CPPickerView#5]
First, I really like this control!
I was in need for a compact hour/minutes selection, and the standard DatePicker cover half the screen....

But I noticed that as soon as I used the peekInset property, the area where the scrollView tracks the scrolling also gets smaller.

I do realize why, but it really compromises the usability, and basically makes the control annoying to use...
So I can't use the insets, and the GUI loses out on the visual hints that there are more data available...

Can You come up with a solution to make the whole pickerView sensitive for tracking even when we are using the peekInsets?

**Comment by cbpowell** [comment]
Glad you like it!

I see what you mean, with a large peekInset you'd end up with a tiny touchable area. I did a bit of searching as I figured someone else using paging UIScrollViews had probably ran into this before, and found [this helpful stackoverflow answer](http://stackoverflow.com/a/1220605/580913).

I implemented that in the latest commit, seems to work pretty well for me - check it out!

**Comment by Janne-M** [comment]
Wow! that was fast!

... a bit too fast though... :-D

I guess You forgot to check in the CPPickerView.m, since it's only the viewController that are updated.  ;-)

But I modified the hitTest method in CPPickerView.m with:  return [self.subviews objectAtIndex:0];

And it all worked fine!

**Comment by cbpowell** [comment]
Whoops I should have said "latest commit**s**". The commit just before the last one, commit 5d03eb8480b9e609ecee19656f470fa62f55de50, has my changes to the `hitTest:withEvent:` method.

**Comment by Janne-M** [comment]
Ah.. ok, I did get that code... but that works just as before, as I noticed.

If you return the self.contentView, you will return the same view you shrink with the peekInsets.

Instead, return  [self.subviews objectAtIndex:0] and you will return the view containing the whole scroll view, not just the central label, and it will feel natural to use the whole 'wheel' for scrolling!

**Comment by cbpowell** [comment]
Hmm, strange - I'd think that `self.contentView` (the UIScrollView) would actually be the same as `[self.subviews objectAtIndex:0]`, as it's the first/lowest subview added to the "container" CPPickerView (self, in this case). Not sure why it's not working for you, but good your different solution works. I'll try it both ways later on a device, as I actually only tested on the simulator before.
